version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./newsletter-service-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      
